# Generated by Django 3.1.4 on 2021-07-13 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ums', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customtoken',
            name='expires_time',
            field=models.CharField(default=1626263769.0838737, max_length=30),
        ),
        migrations.DeleteModel(
            name='AccessToken',
        ),
    ]
